config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root "user_sessions#new"
  resources :users, except: %i[ index ]

  get "login" => "user_sessions#new", as: :login
  post "login" => "user_sessions#create"
  get "logout" => "user_sessions#destroy", as: :logout

  resources :schedules, only: %i[ index new create show ] do
    resources :plans, only: %i[ new create edit update destroy ]
    collection do
      post :notifications
    end
  end
end

app/views/shared_pages/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared_pages/_footer.html.erb
<div class="footer" style="background-color:gray">
  <a>利用規約</a>
  <a>プライバシーポリシー</a>
  <a>お問い合わせ</a>
</div>

app/views/shared_pages/_header.html.erb
<div class="header" style="background-color:gray">
  <%= link_to t('defaults.logo'), schedules_path %>
  <% if current_user %>
    <%= link_to t('header.logout'), logout_path %>
  <% else %>
    <%= link_to t('header.create_user'), new_user_path %> |
    <%= link_to t('header.login'), login_path %>
  <% end %>
</div>