config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root "user_sessions#new"
  resources :users, except: %i[ index ]

  get "login" => "user_sessions#new", as: :login
  post "login" => "user_sessions#create"
  get "logout" => "user_sessions#destroy", as: :logout

  resources :schedules, only: %i[ index new create show ] do
    resources :plans, only: %i[ new create edit update destroy ]
    collection do
      post :notifications
    end
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :name, presence: true, length: { maximum: 32 }

  belongs_to :user
  has_many :plans, dependent: :destroy
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :prohibit_interference_with_others, only: %i[ show ]
  before_action :time_define, only: %i[ new create show ]

  def index
    @schedules = current_user.schedules.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to schedule_path(@schedule), success: "#{@schedule.name}を作成しました"
    else
      flash.now[:danger] = "スケジュール表を作成出来ませんでした"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def notifications
    @user = current_user
    PlanNotificationMailer.with(user: @user).on_time.deliver_later
  end

  private

  def time_define
    @time = Time.new(2026, 1, 4, 0, 0, 0)
  end

  def schedule_params
    params.require(:schedule).permit(:name).merge(user_id: current_user.id)
  end

  def prohibit_interference_with_others
    @schedule = Schedule.find(params[:id])
    if @schedule.user != current_user
      redirect_to schedules_path, notice: "他のユーザーへの干渉は許しません。"
    end
  end
end

app/views/schedules/_form.html.erb
<%= form_with model: schedule, method: :post do |f| %>
  <div class="field">
    <%= f.label t('schedules.name') %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "作成" %>
  </div>
<% end %>

app/views/schedules/index.html.erb
<h1><%= t('defaults.logo') %></h1>
<h2>スケジュール管理画面</h2>
<p>現在使用中のスケジュール</p>
<i>スケジュール1(例:普通の日常)</i>
<br>
<% if @schedules %>
  <% @schedules.each do |schedule| %>
    <%= link_to schedule.name, schedule_path(schedule) %>
    <br>
  <% end %>
<% end %>
<%= link_to "+ スケジュール表新規作成", new_schedule_path %>

app/views/schedules/new.html.erb
<h2>スケジュール表新規作成</h2>
<% if @schedule.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= render "form", schedule: @schedule %>

app/views/schedules/show.html.erb
<%= link_to "管理画面に戻る", schedules_path %>

<h2><%= @schedule.name %></h2>

<table>
  <thead>
    <th scope="col">時刻</th>
    <th scope="col">日曜日</th>
    <th scope="col">月曜日</th>
    <th scope="col">火曜日</th>
    <th scope="col">水曜日</th>
    <th scope="col">木曜日</th>
    <th scope="col">金曜日</th>
    <th scope="col">土曜日</th>
  </thead>
  <tbody>
    <% 48.times do |t| %>
      <tr>
      <% time_separate_start = @time + 60 * 30 * t %>
      <% time_separate_end = @time + 60 * 30 * (t + 1) %>
        <th scope="row"><%= "#{time_separate_start.strftime("%H:%M")} ~ #{time_separate_end.strftime("%H:%M")}" %></th>
        <% 7.times do |w| %>
          <td>
            <% schedule_plan = @schedule.plans.find_by(starting_day_of_week: w.to_i, starting_time_before_type_conversion: time_separate_start) %>
            <% if schedule_plan %>
              <%= link_to schedule_plan.name, "/schedules/#{@schedule.id}/plans/#{schedule_plan.id}/edit" %>
            <% else %>
              <%= link_to "+", new_schedule_plan_path(@schedule, starting_day_of_week: w.to_i, starting_time_before_type_conversion: time_separate_start) %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>